
export default {
  host: '',
  port: 50000,
  jwtKey: 'mock', // Generate jwt key text
  ignoreTokenPath: [
    '/swagger/swagger.json',
    '/swagger/swagger',
    '/users/login',
    '/users/register',
    '/healthcheck',
  ], // Skip to verify the interface of the token
  mongodb: 'mongodb://'+ 'admin:123456@' + '10.10.201.38:27018/test?authSource=admin;retryWrites=false', // Database connection string
  locale: 'en', // Current language
  plugins: [
    '@foxpage/foxpage-plugin-aws-s3',
    '@foxpage/foxpage-plugin-ares',
    '@foxpage/foxpage-plugin-unpkg',
  ],
  allLocales: [
    'en-US',
    'zh-HK',
    'en-HK',
    'ko-KR',
    'ja-JP',
    'en-IN',
    'en-CA',
    'es-US',
    'no-NO',
    'da-DK',
    'pt-PT',
    'es-MX',
    'uk-UA',
    'fi-FI',
    'kk-KZ',
    'sv-SE',
    'en-BE',
    'fr-CH',
    'en-CH',
    'fr-BE',
    'nl-BE',
    'de-CH',
    'de-AT',
    'en-IE',
    'ar-SA',
    'ar-AE',
    'ar-XX',
    'en-XX',
    'en-NZ',
    'en-IL',
    'en-SA',
    'en-AE',
    'nl-NL',
    'el-GR',
    'pt-BR',
    'tr-TR',
    'pl-PL',
    'en-TH',
    'en-ID',
    'en-MY',
    'en-KR',
    'en-JP',
    'zh-SG',
    'en-GB',
    'it-IT',
    'zh-TW',
    'tl-PH',
    'vi-VN',
    'en-AU',
    'th-TH',
    'id-ID',
    'ms-MY',
    'en-SG',
    'zh-CN',
    'ru-RU',
    'es-ES',
    'de-DE',
    'fr-FR',
    'ko-KR',
    'ja-JP',
  ], // Supported locales
  storageConfig: {
    bucket: 'foxpage',
    config: {
      region: 'ap-southeast-1',
      credentials: {
        accessKeyId: 'AKIASBTKBMEZFDKETTFX',
        secretAccessKey: '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',
      },
    },
  },
  resourceConfig: {
    ares: {
      registry: 'http://registry.ares.fws.qa.nt.ctripcorp.com',
      static: 'http://static.fws.qa.nt.ctripcorp.com',
    },
    unpkg: {},
  },
};
