// const mongoConfig = process.env.MONGO_CONFIG;

export default {
  host: '',
  port: 50000,
  jwtKey: 'mock',
  ignoreTokenPath: [
    '/swagger/swagger.json',
    '/swagger/swagger',
    '/users/login',
    '/users/register',
    '/healthcheck',
  ],
  mongodb: 'mongodb://'+ 'admin:123456@' + '10.10.201.38:27018/test?authSource=admin;retryWrites=false', // Database connection string
  plugins: ['@foxpage/foxpage-plugin-aws-s3'],
  allLocales: [
    'en-US',
    'zh-HK',
    'en-HK',
    'ko-KR',
    'ja-JP',
    'en-IN',
    'en-CA',
    'es-US',
    'no-NO',
    'da-DK',
    'pt-PT',
    'es-MX',
    'uk-UA',
    'fi-FI',
    'kk-KZ',
    'sv-SE',
    'en-BE',
    'fr-CH',
    'en-CH',
    'fr-BE',
    'nl-BE',
    'de-CH',
    'de-AT',
    'en-IE',
    'ar-SA',
    'ar-AE',
    'ar-XX',
    'en-XX',
    'en-NZ',
    'en-IL',
    'en-SA',
    'en-AE',
    'nl-NL',
    'el-GR',
    'pt-BR',
    'tr-TR',
    'pl-PL',
    'en-TH',
    'en-ID',
    'en-MY',
    'en-KR',
    'en-JP',
    'zh-SG',
    'en-GB',
    'it-IT',
    'zh-TW',
    'tl-PH',
    'vi-VN',
    'en-AU',
    'th-TH',
    'id-ID',
    'ms-MY',
    'en-SG',
    'zh-CN',
    'ru-RU',
    'es-ES',
    'de-DE',
    'fr-FR',
    'ko-KR',
    'ja-JP',
  ],
  resourceConfig: {
    ares: {
      registry:
        'https://3xyfu62yi8.execute-api.ap-southeast-1.amazonaws.com/default/ares-s3-service?urlname=',
      static: 'https://3xyfu62yi8.execute-api.ap-southeast-1.amazonaws.com/default/ares-s3-service?urlname=',
    },
    unpkg: {},
  },
};
